"""followers

Revision ID: 48054562c87e
Revises: cdfae9a3f8f1
Create Date: 2024-08-19 19:52:59.185865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48054562c87e'
down_revision = 'cdfae9a3f8f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
